name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # triggers when you push to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Verify DockerHub Login    
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker info


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mario_level1:satpal

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push   # Wait for the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH keydeploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy container on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "Logging into DockerHub..."
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

            echo "Pulling latest image..."
            docker pull dhankhar9918/mario_level1:satpal

            echo "Stopping and removing old container (if exists)..."
            docker stop mario_level1 || true
            docker rm mario_level1 || true

            echo "Running NEW container..."
            docker run -d --name mario_level1 -p 80:8080 dhankhar9918/mario_level1:satpal
          EOF
